### PR TITLE
Support for MMDVM_HS_Dual_Hat

### PR DESCRIPTION
**Pull request by phl0**
Add Makefile support for duplex variant of MMDVM_HS_Hat.

### CODE REVIEW

**Comment by juribeparada** [comment]
Good!, but can you add the changes also for Configs files in the "configs" folder, probably adding a new config file for your board?. Also a script for binary firmware update in scripts folder.

**Comment by phl0** [comment]
Sure. QRX pls.

**Comment by phl0** [comment]
Like that?

**Comment by juribeparada** [comment]
Only two things:
- Firmware version now is v1.3.3
- The root Config.h should not be modified, copy the original settings for Libre Kit, simplex

**Comment by phl0** [comment]
[x] done.

**Comment by rogerclarkmelbourne** [comment]
This is not really an issue, but can someone tell me where I can find details of the functionality of the Dual Hat board ?

e.g. is it standalone, or does it also connect to the net
And can it be used to link to another repeater e.g. handheld <-- 2m --->  Dual Hat <-- 70cms --> real repeater ??

**Pull request merged**
